apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginapp
  labels:
    app: loginapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loginapp
  template:
    metadata:
      labels:
        app: loginapp
    spec:
      containers:
        - name: frontend
          image: vigneshkumar56/login-app:v1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: loginapp
spec:
  type: NodePort
  selector:
    app: loginapp
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080  # You can choose any port between 30000â€“32767
